### ISSUE TITLE
i have cloned the project and implemented in my own everything is working fine but the css part is missing. is there anything i am unable to do it please help me in this.

### ISSUE THREAD

**Issue by appflowrajesh** [dsalvagni/react-profile-picture#1]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by appflowrajesh** [comment]
![image](https://user-images.githubusercontent.com/19326692/75613405-5f72e580-5b53-11ea-8cbc-ba12cf6d7077.png)

**Comment by appflowrajesh** [comment]
![image](https://user-images.githubusercontent.com/19326692/75613413-77e30000-5b53-11ea-9ae4-568725192fe7.png)

**Comment by appflowrajesh** [comment]
![image](https://user-images.githubusercontent.com/19326692/75613486-3f8ff180-5b54-11ea-8b84-7f4a82c6afc6.png)

**Comment by appflowrajesh** [comment]
![image](https://user-images.githubusercontent.com/19326692/75613491-55051b80-5b54-11ea-9ff6-9e4ada159154.png)

**Comment by dsalvagni** [comment]
It seems that you didn't imported the css file as in the [example](https://github.com/dsalvagni/react-profile-picture#example).

```
import ProfilePicture from "profile-picture"
import "profile-picture/build/ProfilePicture.css"
```

**Comment by appflowrajesh** [comment]
why would i need to import these files if i am not using your npm version. as i said that i have cloned ur project and i have created a separated component of ProfilePicture. so will it be still required to import these things ???

**Comment by appflowrajesh** [comment]
please help me in this sir

**Comment by dsalvagni** [comment]
Are you importing this file?
`import stylesheet from "./sass/ProfilePicture.scss";`

It’s hard to tell without seeing your implementation. Please check if you are importing wherever style sheet you are using and that it has the same class names used by the component. Don’t forget it’s using css modules. Check also if your project support it.

That’s all I can do to help.

This issue is about support (?) and it’s not related to this code, so I’m going to close it.

**Comment by appflowrajesh** [comment]
yes i am doing the same.
 import stylesheet from "./sass/ProfilePicture.scss";
