### ISSUE TITLE
Issue when retrieving image file

### ISSUE THREAD

**Issue by NikolMarg** [dsalvagni/react-profile-picture#13]
Hello! Great work on the project, I love the flow but I can't seem to be able to retrieve the actual file via `this.profilePictureRef.current.getData().file`. I set up a CodeSandbox reproducing the issue as well. 
Any clues?

* **What is the current behavior?**
Using the basic example provided, `imageData.file` appears to be undefined.

* **Please provide a minimal demo of the problem**
https://codesandbox.io/s/vigilant-architecture-p2g73

* **What is the expected behavior?**
`imageData.file` should contain the image file for submission.

**Comment by tumenor** [comment]
Hi!

I don't have a fix for the actual problem, but I have from finding a neat function online (I would give credit if I recalled the place) which solves this for me.

https://codesandbox.io/s/quirky-bush-cb4z0?file=/src/App.js

Here I've attached a fork of your sandbox with a solution :)
Hope it helps!

**Comment by dsalvagni** [comment]
@NikolMarg thank you for the feedback and for submitting the issue. Will make a quick fix for it.

@tumenor thanks for sharing your workaround for this issue!
