### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by sifloz** [dsalvagni/react-profile-picture#19]
I'm submitting a bug report. When I try to handle my uploaded image I got the following error: 

Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

I'm testing react-profile-picture on my localhost and I'm not able to store or preview the picture because of that error.

Here's my code, which is the same as the page example:

```
const handleUpload = () => {
        const PP = profilePictureRef.current;
        const imageData = PP.getData();
        const file = imageData.file;
        const imageAsDataURL = PP.getImageAsDataUrl();
     
        //add here the upload logic...
    }
```

I created the profilePictureRef reference using the following code:

`const profilePictureRef = useRef();`

As you can see, I'm currently using a function componente and React hooks.

**Comment by mjwrona** [comment]
Hi @sifloz 

Had the same issue.

`img.crossOrigin = 'Anonymous';`

did not work for me so i implemented a workaround:

```
getStartupImage() {
        fetch('_IMAGEURL_')
        .then(response => response.blob())
        .then(blob => {
            const PP:any = this.profilePictureRef.current;
            PP.setImage(blob)
        })
}
```

**Comment by samelson1** [comment]
I am also having this issue, @mjwrona 's fix does not work for me I'm afraid. Any news on this?

**Comment by samelson1** [comment]
Found the issue to be located within "ProcessFile.js". The logic does not seem to be working correctly to set the image cross origin. 

I do not have the tools to push a fix to I have fudged it by modifying the build file to manually set the cross origin. 

Code where I have made the change:
![image](https://user-images.githubusercontent.com/28952359/103040748-5765b580-456c-11eb-9e9c-48f866d0ff6c.png)

Modification I made to the build file if anyone needs a quick fix: (located at node_modules/profile-picture/build/index.js )
![image](https://user-images.githubusercontent.com/28952359/103040857-9eec4180-456c-11eb-9213-4daaecf9cd27.png)

Replace "var a=new Image,o" with "var a=new Image();a.crossOrigin='anonymous';var o"

**Comment by dsalvagni** [comment]
@samelson1 @mjwrona @sifloz Hi there, thanks for reporting this and I apologise for the late reply on this topic. I had been quite busy in this particular year, but it's great to see that this component is useful for you - even thought it has some bugs.

The solution you provided @samelson1 might work for all scenarios, even for the `Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.` mentioned above. I'll try to reproduce it and perform some tests. As soon I'm done, I'm going to push a new version.

Enjoy Xmas times & keep safe.
