### ISSUE TITLE
Dragging incorrect file from given window showing hour glass for indefinite period of time 

### ISSUE THREAD

**Issue by vparade** [dsalvagni/react-profile-picture#30]
Issues on Safari browser.

When the user tries to upload SVG or HTML file, hour glass for indefinite period of time 

Video Link: **https://www.loom.com/share/377f9fdeb3c74063bcd80e3a5502bf11**

current Behavior:
Dragging incorrect file from given window showing hour glass for indefinite period of time 

Required Behavior :
When the user tries to upload any another file then image need to show a validation message or reset the state.

**Comment by dsalvagni** [comment]
Fixed
