### ISSUE TITLE
iPhone6 orientation of picture taken from camera is wrong

### ISSUE THREAD

**Issue by akesh-1997** [dsalvagni/react-profile-picture#35]
not sure we have a method to control this but could not locate in manual.

implemented this in an app done in reactjs + capacitorjs. when test in a real device (iPhone6), the picture taken from the Camera gets loaded into the cropper with wrong orientation. 

a selfie image which is portrait gets loaded in to the cropper as a landscape picture. 

the picture should follow the correct orientation which it is taken, or cropper needs orientation adjustment (90`, 180` left or right) controls so the user can adjust by tapping rotate left or right.

or, is there a callback method to get the exif data or current orientation to implement a fix?

**Comment by dsalvagni** [comment]
I think this is not an issue from this lib, but a setting from capacitorjs. 
If you use the demo version on a mobile browser, it works well.

Have you checked this configuration on capacitorjs? It's enabled by default.

````
correctOrientation | boolean | Whether to automatically rotate the image “up” to correct for orientation in portrait mode | : true | 1.0.0
````
https://capacitorjs.com/docs/apis/camera 

It seems to have a fix for it as well: https://www.npmjs.com/package/fix-orientation-capacitor

**Comment by akesh-1997** [comment]
thanks for the reply. just to make my issues little more clear to you.

i visited the  demo page https://salvagni.dev/react-profile-picture/ using an iPhone Safari app. then,

1. lanched the menu by tapping on drop area. 
2. from the 3 options 'take photo', 'gallery', 'browse' i took the option "take photo". 
3. the camera opened fine and i took a photo. 
4. the photo loaded from camera in drop area was rotated 90 degrees. this shuld appear in drop area in right orientation of the camera

i think this is something we can fix in this plugin. please corret me if i'm wrong. 

please see this screenshot taken.. 
![IMG_0015](https://user-images.githubusercontent.com/78068537/136731287-13f611ef-59fd-4534-8377-a97d22d71e39.PNG)
